### ISSUE TITLE
Softnms directory error

### ISSUE THREAD

**Issue by houzhijian** [JunweiLiang/Object_Detection_Tracking#1]
Hi, thanks for sharing. 

Following your inference procedure, when I run step two,
python obj_detect.py --model_path obj_v3_model --version 3 --video_dir v1-val_testvideos \
--video_lst_file v1-val_testvideos.lst --out_dir test_json_out --frame_gap 1 --visualize \
--vis_path test_vis_out --get_box_feat --box_feat_path test_box_feat_out

I got this error
Traceback (most recent call last):
  File "obj_detect.py", line 17, in <module>
    from models import get_model
  File "/home/james/Object_Detection_Tracking/models.py", line 6, in <module>
    from utils import Dataset, get_all_anchors, draw_boxes, box_wh_to_x1x2, get_op_tensor_name
  File "/home/james/Object_Detection_Tracking/utils.py", line 17, in <module>
    from nn import soft_nms,nms
  File "/home/james/Object_Detection_Tracking/nn.py", line 20, in <module>
    from softnms.cpu_nms import cpu_soft_nms, cpu_nms # Uhuh
ImportError: No module named cpu_nms

and I delete the try-except sentence in nn.py
then I got this error
Traceback (most recent call last):
  File "obj_detect.py", line 17, in <module>
    from models import get_model
  File "/home/james/Object_Detection_Tracking/models.py", line 6, in <module>
    from utils import Dataset, get_all_anchors, draw_boxes, box_wh_to_x1x2, get_op_tensor_name
  File "/home/james/Object_Detection_Tracking/utils.py", line 17, in <module>
    from nn import soft_nms,nms
  File "/home/james/Object_Detection_Tracking/nn.py", line 20, in <module>
    from softnms.nms import cpu_soft_nm
ImportError: /home/james/Object_Detection_Tracking/softnms/nms.so: undefined symbol: PyFPE_jbuf

It seems that you don't have cpu_nms module and It may have a problem in nms.so code in softnms file directory...

**Comment by JunweiLiang** [comment]
That is because you use a different numpy than mine. You need to rebuild the *.so files. But I have removed all the cpu_nms and soft_nms in the latest version as they are not used.
