### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.

### ISSUE THREAD

**Issue by devendraswamy** [JunweiLiang/Object_Detection_Tracking#19]
python obj_detect_tracking.py --model_path obj_v3_model --version 3 --video_dir v1-val_testvideos --video_lst_file v1-val_testvideos.lst --frame_gap 1 --get_tracking --tracking_dir test_track_out --out_dir test_json_out --visualize --vis_path test_vis_out --frame_gap 8
  0%|                                                                                                                                   | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv0/Conv2D}}]]
	 [[fastrcnn_predictions/map/while/Neg_1/_1247]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv0/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "obj_detect_tracking.py", line 640, in <module>
    sess_input, feed_dict=feed_dict)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv0/Conv2D (defined at /media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[fastrcnn_predictions/map/while/Neg_1/_1247]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv0/Conv2D (defined at /media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'conv0/Conv2D':
  File "obj_detect_tracking.py", line 510, in <module>
    model = get_model(args, args.gpuid_start, controller=args.controller)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/models.py", line 110, in get_model
    model = Mask_RCNN_FPN(config, gpuid=gpuid)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/models.py", line 303, in __init__
    self.build_forward()
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/models.py", line 490, in build_forward
    use_se=config.use_se, use_resnext=config.use_resnext)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/nn.py", line 886, in resnet_fpn_backbone
    scope="conv0", use_bias=False, data_format="NCHW")
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/nn.py", line 369, in conv2d
    x, W, stride, padding, dilations=dilations, data_format=data_format)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2010, in conv2d
    name=name)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by JunweiLiang** [comment]
This means you have not correctly installed Tensorflow-gpu. Try CUDA 10.0 and cuDNN 7.6 and Tensorflow-gpu 1.15.2. Also, why did you use two different `--frame_gap` in the same command?

**Comment by devendraswamy** [comment]
i tried with cuda 10 , tensorflow-gpu==1.15.2 but again same error 
python obj_detect_tracking.py --model_path obj_v3_model --version 3 --video_dir v1-val_testvideos --video_lst_file v1-val_testvideos.lst --get_tracking --tracking_dir test_track_out --out_dir test_json_out --visualize --vis_path test_vis_out --frame_gap 1
  0%|                                                                                                                                   | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv0/Conv2D}}]]
	 [[fastrcnn_predictions/map/while/Neg_1/_1247]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv0/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "obj_detect_tracking.py", line 640, in <module>
    sess_input, feed_dict=feed_dict)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv0/Conv2D (defined at /media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[fastrcnn_predictions/map/while/Neg_1/_1247]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node conv0/Conv2D (defined at /media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'conv0/Conv2D':
  File "obj_detect_tracking.py", line 510, in <module>
    model = get_model(args, args.gpuid_start, controller=args.controller)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/models.py", line 110, in get_model
    model = Mask_RCNN_FPN(config, gpuid=gpuid)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/models.py", line 303, in __init__
    self.build_forward()
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/models.py", line 490, in build_forward
    use_se=config.use_se, use_resnext=config.use_resnext)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/nn.py", line 886, in resnet_fpn_backbone
    scope="conv0", use_bias=False, data_format="NCHW")
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/nn.py", line 369, in conv2d
    x, W, stride, padding, dilations=dilations, data_format=data_format)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2010, in conv2d
    name=name)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/media/user1/storage-1/Devendra/object_track/Object_Detection_Tracking/myenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by JunweiLiang** [comment]
You'll need to install cuDNN 7.6. Please follow the official [Tensorflow guide](https://www.tensorflow.org/install/gpu) to install gpu support. In my experience, you could download cuDNN libraries from [here](https://developer.nvidia.com/rdp/form/cudnn-download-survey) and then copy the headers and lib64 to `/usr/local/cuda-10.0/`.

**Comment by devendraswamy** [comment]
Thank you I will try
