### ISSUE TITLE
Error：numpy.ufunc size changed, may indicate binary incompatibility. 

### ISSUE THREAD

**Issue by MaureenLmy** [JunweiLiang/Object_Detection_Tracking#7]
I got the error when running object detection on the test videos. I tried numpy 1.14.5 and 1.13.3 and it didn't work.By the way I used python2.7 and tensorflow-gpu 1.10.

Traceback (most recent call last):
  File "obj_detect.py", line 17, in <module>
    from models import get_model
  File "/userhome/34/myliu2/geog/Object_Detection_Tracking/models.py", line 6, in <module>
    from utils import Dataset, get_all_anchors, draw_boxes, box_wh_to_x1x2, get_op_tensor_name
  File "/userhome/34/myliu2/geog/Object_Detection_Tracking/utils.py", line 12, in <module>
    import pycocotools.mask as cocomask
  File "/userhome/34/myliu2/anaconda3/envs/python27/lib/python2.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 918, in init pycocotools._mask
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by JunweiLiang** [comment]
This seems to because your numpy version doesn't match the one used in pycocotools.
